# Generated by Django 3.0.3 on 2020-08-28 19:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
        ('areaprops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('builder', models.CharField(max_length=200)),
                ('rera_id', models.CharField(max_length=200)),
                ('project_id', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(default='bhopal', max_length=30)),
                ('state', models.CharField(default='MP', max_length=30)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('security', 'security'), ('gymnasium', 'gymnasium'), ('waste disposal', 'waste disposal'), ('reserved parking', 'reserved_parking'), ('lift', 'lift'), ('club house', 'club house'), ('shopping center', 'shopping center'), ('rain water harvesting', 'rain water harvesting'), ('water plant', 'water plant'), ('landscape garden', 'landscape garden'), ('kids play area', 'kids play area'), ('cctv', 'cctv'), ('cycle track', 'cycle track')], max_length=165)),
                ('price_start', models.IntegerField()),
                ('price_end', models.IntegerField()),
                ('area_start', models.IntegerField()),
                ('area_end', models.IntegerField()),
                ('property_type', models.CharField(choices=[('1/2/3 BHK APARTMENT', '1/2/3 BHK APARTMENT'), ('1/2 BHK APARTMENT', '1/2 BHK APARTMENT'), ('1 BHK APARTMENT', '1 BHK APARTMENT'), ('2 BHK APARTMENT', '2 BHK APARTMENT'), ('3 BHK APARTMENT', '3 BHK APARTMENT'), ('3 BHK DUPLEX', '3 BHK DUPLEX'), ('2 BHK DUPLEX', '2 BHK DUPLEX'), ('VILLA', 'VILLA'), ('BUNGALOW', 'BUNGALOW'), ('PLOT', 'PLOT'), ('PENTHOUSE', 'PENTHOUSE')], max_length=30)),
                ('possesion', models.CharField(max_length=20)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='areaprops.Area')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
    ]
